M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date Thu 13 Oct 2022 10:08:00 PM MDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-13T22:08:00-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X205.2Y-156.05
X205.2Y-163.55
T2
X103.5Y-103.5
X103.5Y-168.5
X212.5Y-103.5
X212.5Y-168.5
T0
M30
